vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
#pour configurer le directory des images téléchargées
    mappings:
        photo:
            uri_prefix: /img/profil
            upload_destination: '%kernel.project_dir%/public/img/profil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false #true : chargement de l'image lors du chargement de l'entité - création d'une instance File
            delete_on_update: true #fichier effacé si nouvel upload
            delete_on_remove: true #fichier effacé si user supprimé
